// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CommentWrap
{
	internal sealed partial class Vsix
	{
		public const string Id = "CommentWrap.01a661ba-bd46-4bb0-992b-6fba3cec0f94";
		public const string Name = "CommentWrap";
		public const string Description = @"Empty VSIX Project.";
		public const string Language = "en-US";
		public const string Version = "1.0";
		public const string Author = "jackson a";
		public const string Tags = "";
	}
}
