// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CommentWrap
{
    internal sealed partial class Vsix
    {
        public const string Id = "CommentWrap.01a661ba-bd46-4bb0-992b-6fba3cec0f94";
        public const string Name = "CommentWrap";
        public const string Description = @"A comment-wrapping extension. Set cursor inside comment and activate with `Alt+Q`.";
        public const string Language = "en-US";
        public const string Version = "0.9";
        public const string Author = "fairybow";
        public const string Tags = "";
        public const bool IsPreview = true;
    }
}
